### ISSUE TITLE
[FEAT]  Create Email and password session

### ISSUE THREAD

**Issue by nove1398** [PinguApps/AppwriteSdk#138]
### Describe the feature

Implement the email and password session on the server side sdk.

**Comment by pingu2k4** [comment]
Good spot, We do need a server implementation of this. I had marked it as not to be implemented for server. Will get to this. Thanks.

**Comment by nove1398** [comment]
Yay! Quick response, i love it. If you have implementation questions will be happy too discuss approaches of needed.

**Comment by nove1398** [comment]
I believe there are some you just added to fill out the road map. I will add more as i look through

**Comment by pingu2k4** [comment]
Hey,

Based on this I added 5 endpoints to the server SDK for account API, including create email and password session in #144 

I've also just implemented create email and password session in #149 too.

Apologies for the delay, have been on holidays etc but should be more active again now that's all over.

**Comment by nove1398** [comment]
That is fine, everyone needs to reset. And i have been checking on this
project almost daily. Looking forward to trying these new features too
