### ISSUE TITLE
[FEAT] Implement Users - Create User JWT

### ISSUE THREAD

**Issue by pingu2k4** [PinguApps/AppwriteSdk#227]
### Describe the feature

Implement Users - Create User JWT

**Comment by Nove-smp** [comment]
Will the be a server implementation for creating jwt?

**Comment by pingu2k4** [comment]
The users API is exclusive to the server, so yes this will be within the server SDK. :)

In a branch, I've already commited an update to the readme to include this in the roadmap displayed for the Users API section - It wasn't there before EITHER because I missed it when originally creating the roadmap, OR because it was recently added.

**Comment by pingu2k4** [comment]
The commit in question, adding CreateJWT to the Users section, as a server endpoint to the roadmap: https://github.com/PinguApps/AppwriteSdk/commit/2a98939725dd63a03c5fbf305448fe582aa0c361

**Comment by Nove-smp** [comment]
Noted
