### ISSUE TITLE
[Question] Will Realtime be supported?

### ISSUE THREAD

**Issue by MeisterDerMagie** [PinguApps/AppwriteSdk#513]
### Question

The title says it all. Is Realtime support planned?

**Comment by pingu2k4** [comment]
Hey :)

Initially, for a first version (to hit V1) it is not planned.

However, soon after V1, once everything appears stable and complete, I plan to work on Realtime at that point. It will by its nature be very different to the regular rest stuff, and so I imagine that it will reside in a seperate project / seperate nuget package, which gives the option of adding when needed, or not when it isn't.

The priority is on supporting all of Appwrite's REST endpoints, but once that is complete realtime is one of the next (possible the next) things to tackle. :)

**Comment by MeisterDerMagie** [comment]
Thanks for the info! I'll see if I can implement something by myself until then. 👍🏼

**Comment by nove1398** [comment]
Perhaps you could add, it to this package still. It's not a rest call but you could tack it in as a wss implementation right?

**Comment by pingu2k4** [comment]
@nove1398 Having it seperate makes more sense. Utilities that realtime will require have little crossover with rest API requirements. If your project needs both, you can simply install both packages and be totally fine. Another benefit of splitting it up, is that it means you can reduce the binary size if you only need one part or the other, which might be particularly handy for those using Blazor WASM for example. :)

**Comment by nove1398** [comment]
Agreed that make sense

**Comment by MeisterDerMagie** [comment]
I'll see if it makes sense to share my version of realtime for .NET. I need it for a game made with Unity which always has it's own way of doing things. So it might not be suitable for an non-Unity use case.

**Comment by pingu2k4** [comment]
Hey @MeisterDerMagie - Apologies for how long it took, but Realtime support has now been released in a third nuget package. :)

**Comment by MeisterDerMagie** [comment]
Big news! Thank you very much for the work you put in it!
