### ISSUE TITLE
[Task] Add todo to issue action

### ISSUE THREAD

**Issue by pingu2k4** [PinguApps/AppwriteSdk#521]
### Task Details

[action](https://github.com/marketplace/actions/todo-to-issue)

**Comment by nove1398** [comment]
What's this?

**Comment by pingu2k4** [comment]
> What's this?

This will create issues whenever it finds `// TODO` comments in any code, so that they don't get forgotten about.

**Comment by nove1398** [comment]
This is really cool, proceed with implementation. #PR approved
